### ISSUE TITLE
TracingAllocator + http_init + http_cleanup + ASAN segfault

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-c-common#688]
with `AWS_MEMTRACE_STACKS` and the allocator provided by `aws_mem_tracer_new`, calling `aws_http_library_init` followed by `aws_http_library_cleanup` causes a SEGV:

```
==47935==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010759d723 bp 0x7000098c5710 sp 0x7000098c56d0 T4)
==47935==The signal is caused by a READ memory access.
==47935==Hint: address points to the zero page.
    #0 0x10759d723 in aws_hash_table_find hash_table.c:413
    #1 0x1075a04d9 in s_alloc_tracer_untrack memtrace.c:190
    #2 0x1075a0195 in s_trace_mem_release memtrace.c:441
    #3 0x10759d613 in aws_hash_table_clean_up hash_table.c:271
    #4 0x107594947 in aws_http_library_clean_up http.c:470
    #5 0x1066fa1f8 in aws_crt::http::clean_up::hee41a875d61c2824 mod.rs:23
    #6 0x10671fb58 in aws_crt::library_clean_up::h3e1713a99b77da82 lib.rs:171
```

This doesn't happen with `AWS_MEMTRACE_NONE` or `AWS_MEMTRACE_BYTES`

**Comment by jmklix** [comment]
Fixed with this PR: https://github.com/awslabs/aws-c-common/commit/d09b75e8fa20e3f27cb02c0458bd69dc854fc3f2
